### ISSUE TITLE
Contributors guidelines

### ISSUE THREAD

**Issue by lbenie** [azachar/angular-language-picker#11]
I've looked around and found this as a template for commit messages:

``` sh
If applied, this commit will be a
[] New feature
[] Bug fix
[] Enhancement

Why was this change made ?

Any reference to issues, articles, etc. ?
```

Thoughts ? @azachar

**Comment by lbenie** [comment]
To integrate this all you have to do is

``` sh
$ git config --global commit.template ~/path/to/file.txt
```

**Comment by azachar** [comment]
Hello @lbenie,

Let's follow some big guys : https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#commit

I really like how they commit messages look like. 

Also it would be great to use a changelog generator such https://github.com/skywinder/github-changelog-generator

What do you think about it?

Cheers,
Andrej

**Comment by lbenie** [comment]
@azachar 

Yes ! 
It looks promising. Also I will fix my PR when i get to work.

:+1: for the labels btw !
