### ISSUE TITLE
changelog generator

### ISSUE THREAD

**Issue by azachar** [azachar/angular-language-picker#15]
Hi there, 
it would be great to have this integrated.

https://github.com/skywinder/github-changelog-generator

**Comment by azachar** [comment]
@lbenie could you help with this too?

**Comment by lbenie** [comment]
Yes i will look into it.

I'll first close #7 #8 #14. Then I will sure take a look for that. I agree this is something somewhat critical it would help us a lot.

I will be sending some PR in the next hour or so

Keep posted !
