### ISSUE TITLE
Feature : Gulp task runner instead of grunt

### ISSUE THREAD

**Issue by lbenie** [azachar/angular-language-picker#7]
Proposal : Use gulp instead of grunt for automating tasks.

Gulp uses streams instead of temp files and is way more readable than grunt.

I will work on a feature branch and submit a PR

Also I will add some tests 

let me know what you think ?

**Comment by azachar** [comment]
Gulp sounds great time! You are welcome to provide any support here :)

**Comment by azachar** [comment]
Please create a separate branch where you squish all changes related to gulp feature. Then provide this as a PR. Thanks a lot!

**Comment by lbenie** [comment]
PR created here : #10

**Comment by lbenie** [comment]
@azachar 

I'm still working on the gulp feature. I've done all the task and added support for #8

I'm in the process of testing the resulting directive. Haven't had the time so far.

PR coming later this week

**Comment by azachar** [comment]
@lbenie You are the king! Thanks a lot! I look forward for your contributions :)

**Comment by azachar** [comment]
Hey @lbenie, 
how are you?

I think the best would be to follow some best practices for the project structure for a plugin build by gulp.

I did some research http://stackoverflow.com/questions/35394400/generator-for-angular-library and I think the best is to go with https://github.com/Wooooo/generator-angular-plugin

We will get a lot of features out of box. 

Look forward hearing from you.

Cheers,
Andrej

**Comment by lbenie** [comment]
hey @azachar 
sorry i have been swamped with work and the gf !

i've just take a look and yeah it seems like a nice plugin. :smile: 

i have my gulp files but couldn't get the same behaviour with the modal i think. 

i've tested my changes locally but it wasn't working.

maybe you can add another branch: gulp
and we could use that generator on the side until it's ready to go for production ? let me know what you think ?

**Comment by azachar** [comment]
Nice to hear from Lucién,
I am playing with gulp based on that plugin. But frankly, the generator is not production ready yet. 

I added so many basic features, but good thing is, that the building is done. Now I am playing with karma, tests and dependency injections. I will let you know when it is done :)

**Comment by lbenie** [comment]
cool let me know when we have a basic project that we can start from :+1: 

it would definetly add a nice structure for readability and scalability
I quickly glanced at the generated project and yes some features are missing but it's a nice start...

we must ensure we have these features in place
- [x] jade
- [x] stylus
- [x] stylint
- [x] coffeescript
- [ ] jshint
- [ ] jscs
- [ ] jadelint
- [x] editorconfig
- [x] gitattributes
- [x] gitignore
- [x] commitizen
- [x] travis
- [x] karma + mocha + chai

**Comment by azachar** [comment]
Hey @lbenie, I just pushed the branch jade. Have a look at it and feel free to improve it.

**Comment by lbenie** [comment]
cool checking it right now !

**Comment by azachar** [comment]
I just found that languageMappingList is not included as it should be...

**Comment by lbenie** [comment]
taking a look at it this morning.

also #17.

**Comment by lbenie** [comment]
@azachar i've updated the list of features that we [need](https://github.com/azachar/angular-language-picker/issues/7#issuecomment-184025255)
